(define (domain network)
  (:requirements :strips)
  (:predicates
	 (task ?x)
	 (depends ?x ?y)
	 (is-running ?x)
	 (output-port ?x)
	 (input-port ?x)
	 (has-output ?x ?y)
	 (has-input ?x ?y)
	 (is-connected ?x ?y)
	 (should-connected ?x ?y ?z)
)
(:action start :parameters (?r ?t)
 :precondition (and (task ?t))
 :effect (and    (is-running ?t) (depends ?r ?t) )
)
(:action stop :parameters (?t)
 :precondition (not (depends _ ?t))
 :effect (not    (is-running ?t))
)
)
