
bundle:
    dependencies:
        - rock
        - rock.dfki
        - avalon 
          #        - rock_auv
        - auv 
        - sauce 

log:
    #    filter_backtraces: false
    #events: true
    #dir: /mnt/logs/new
    # logging Roby into file: logs/<date>/<file>.txt
    levels:
        #        roby/execution_engine: INFO
        #syskit: DEBUG
        #roby: DEBUG
        #syskit/models: DEBUG
        #syskit/instance_requirements: DEBUG
        #syskit/network_generation: DEBUG
        #syskit/network_generation/merge_solver: DEBUG
        #syskit/network_generation/engine: DEBUG
        #syskit/component: DEBUG
